name: OpenSSF Scorecard

on:
  schedule:
    - cron: '30 1 * * 0' # weekly
  push:
  pull_request:

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
        continue-on-error: true
