name: OpenSSF Scorecard

on:
  push:
  pull_request:
  schedule:
    - cron: '30 1 * * 0'  

permissions:
  contents: read
  actions: read
  id-token: write
  security-events: write
  checks: write  

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2.4.1 ##
        with:
          results_file: results.sarif
          publish_results: true
        continue-on-error: false

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
