name: OpenSSF Scorecard

on:
  push:
  pull_request:
  schedule:
    - cron: '30 1 * * 0'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scorecards analysis
        uses: ossf/scorecard-action@v2.1.0
        with:
          results_file: results.sarif
          publish_results: true
        continue-on-error: true
